title: Home
pages: true
files: 
  fields: true
    title:
      label: Title
      type:  text
    caption:
      label: Caption
      type:  textarea
    position:
      label: Position
      type: select
      options: ['center', 'top', 'left', 'right', 'bottom']
      help: Fit image direction  
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  style:
    label: Estilo
    type:  text    